### ISSUE TITLE
Differentiate blocked users

### ISSUE THREAD

**Issue by losuler** [scholtzm/punk#35] opened 2017-02-14 02:03 UTC
### Issue description
Currently blocked users are indistinguishable from other offline friends. 

### Suggestions
Potential ways I think this could be dealt with are:

- Altering their status to "Blocked" with the text colored red (similar to how they appear on the steam web interface, [as seen here](https://i.imgur.com/MgkEqn0.png)).

- Hiding them from the friends list all together (this is how the Steam client manages it).

**Comment by scholtzm** [comment] 2017-02-14 07:51
Thank you for your suggestions, I'll probably go with option number two. Just need to find someone to block. 😄

**Comment by scholtzm** [comment] 2017-06-11 11:37
It's been a while since this report but I finally looked at this and I'm not able to reproduce this behaviour.

There are 4 people who I permanently blocked, they do not appear in my Punk friends list.

I have also tried blocking my friend, his name instantly disappeared from Punk friends list. After unblocking him via steamcommunity.com, his name instantly reappears in my friends list.

Can you provide steps to reproduce this behaviour?

**Comment by losuler** [comment] 2017-06-13 05:41
In looking into this, these were the following steps I took and the observations I made from them. 

- Blocked a friend with **Punk**.
  - They disappear from **Punk**'s friends list.
  - They cannot be unblocked with **Punk** (as they remain hidden, even after subsequent restarts). 
  - They appear in the **Steam client**'s friends list at the bottom in white, with the status `Blocked`.

- Blocked a friend with the **Steam client**.
  - They appear in **Punk**'s friends list as offline and in alphabetical order (with other offline friends).
  - They cannot be unblocked with **Punk** (right click menu assumes they are any other offline friend). 
  - They appear in the **Steam client**'s friends list at the bottom in white, with the status `Blocked`.

_Note_: To ensure my observations weren't effected in anyway by #36, I made sure neither clients were running simultaneously. I also newly cloned and built Punk before I went ahead with the above.

Now beyond this, I discovered that people that I had blocked but which were not still my friends appeared in **Punk** at the bottom of the friends list as offline. Whereas in the **Steam client** these people didn't appear in my friends list at all, and were only accessible through the Steam website under `Profile >> Friends >> Blocked List`.

**Comment by scholtzm** [comment] 2017-06-13 06:36
Thank you for a very thorough description, I will look into it this week. 👍

**Comment by scholtzm** [comment] 2017-06-18 21:59
@losuler 

Ok, so I have been digging into this issue and I managed to reproduce all 3 cases you described. Handling of blocked users is broken right now and I'll need to do some adjustments to `personastate` plugin which handles the friends list.

Relevant bits from SteamKit:
https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/Handlers/SteamFriends/SteamFriends.cs#L737
https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/Handlers/SteamFriends/SteamFriends.cs#L647

**Comment by scholtzm** [comment] 2017-06-19 21:46
Should be fixed in https://github.com/scholtzm/punk/commit/e6c4bffad13b05df0d46588de1f2e9baa6400f69 @ master.

Next release will contain this fix.

**Closed as completed** 2017-06-19 21:46 UTC
Labels: bug
